Fix/mer 81 price threshold
dividohq/finance-plugin-magento2 pull request #107
Opened 2022-02-08 12:34 UTC by dbelkad

2022-02-08 12:49 UTC, andivido commented on CHANGELOG.md
> +- feat: shows payment method logo on checkout pageO
🙃

2022-02-08 13:05 UTC, dbelkad commented on CHANGELOG.md
> +- feat: shows payment method logo on checkout pageO
Wait, was that me? 👀  Ooops, lemme revert real quick. Soz 😅

2022-02-08 13:36 UTC, joelbitar commented on Block/Product/View/Widget.php
> +        if ($threshold === false || $this->getProductAmount() < $threshold) {
It would not hurt with some documentation on _why_ we are getting the product amount now

2022-02-08 13:37 UTC, joelbitar requested changes
Could we remove all the formatting changes, makes it hard to read the PR

2022-02-08 14:03 UTC, andivido approved these changes

2022-02-08 15:11 UTC, joelbitar commented on Block/Product/View/Widget.php
> +        if ($threshold === false || $this->getProductAmount() < $threshold) {
As if you are explaining it to someone else, or yourself :)

2022-02-08 15:44 UTC, dbelkad commented on Block/Product/View/Widget.php
> +        if ($threshold === false || $this->getProductAmount() < $threshold) {
Before I put this inside the codebase, I want to run this by you. This would be my documentation:
` /*
    3 years ago, Jonas Hassel wrote a function called getAmount() which was then later renamed to 
    getProductAmount() by Andrew Smith who, I'm guessing, forgot to update this instance of the old code 
    which broke the logic, I then spotted this and updated the name of the function to match the new name
   */`
Is this ok?

2022-02-09 09:05 UTC, joelbitar commented on Block/Product/View/Widget.php
> +        if ($threshold === false || $this->getProductAmount() < $threshold) {
@dbelkad no need to point fingers or explain the history of the codebase. What I was after was why we needed to update to use the productAmount now, as opposed to the old function. Since it was a typo and we never had any use of getAmount that point is moot.

If however I was to document it I would write a line or two explaining what the code does, ie.
// Check that there is a threshold and that the cost of the current product is below that threshold

2022-02-09 09:18 UTC, dbelkad commented on Block/Product/View/Widget.php
> +        if ($threshold === false || $this->getProductAmount() < $threshold) {
Ok, sorry, I was reading too much into it. I was a bit confused as the whole file had no documentation whatsoever and also because I didn't really create any new function, or link I didn't feel the need to add an explanation now, if you catch my drift. Either way, I will add your suggested comment and hopefully that will close this case.

2022-02-09 10:26 UTC, nunocosta-divido commented on Block/Product/View/Widget.php
> +        if ($threshold === false || $this->getProductAmount() < $threshold) {
that's why we need phpstan

it would caught all this stuff

2022-02-09 10:58 UTC, simeon-anastasov-divido commented on Block/Product/View/Widget.php
> +        if ($threshold === false || $this->getProductAmount() < $threshold) {
@nunocosta-divido Can't agree more, but on such project where the codebase is more or less shaped by an external framework... is it wise to run such check in Actions - it might flag too many things that are not actually a problem? Maybe update the Makefile with additional target and run it in a container locally instead (and put a reminder to run in the PR checklist) ?

2022-02-09 11:56 UTC, joelbitar reviewed
do we need to cast before we multipl?

2022-02-09 11:56 UTC, joelbitar commented on Block/Product/View/Widget.php
> +                $threshold = (empty($this->helper->getPriceThreshold())) ? 0 : (int)($this->helper->getPriceThreshold() * 100);
Are we sure that getPriceThreshold always return a number that we can multiply with 100, or do we need to cast it to a float before we do the multiplication? so we dont get any nasty errors...

2022-02-09 11:58 UTC, dbelkad commented on Block/Product/View/Widget.php
> +                $threshold = (empty($this->helper->getPriceThreshold())) ? 0 : (int)($this->helper->getPriceThreshold() * 100);
I think me and @andivido already tested for this and the test passed.

2022-02-09 15:25 UTC, dbelkad commented on Block/Product/View/Widget.php
> +                $threshold = (empty($this->helper->getPriceThreshold())) ? 0 : (int)($this->helper->getPriceThreshold() * 100);
Ok, so a little update on this. We're not getting errors however we didn't take into account a human error, so we are now sanitising the data coming from the Config file and then cast it to a float, then in the Widget we do the further conversions to achieve the results we need for the calculations. Will push the changes shortly.

2022-02-15 11:01 UTC, simeon-anastasov-divido requested changes
@dbelkad please have a look at my last comment.

2022-02-15 11:01 UTC, simeon-anastasov-divido commented on Block/Product/View/Widget.php
>                  $threshold = (empty($this->helper->getPriceThreshold())) ? 0 : (int)($this->helper->getPriceThreshold() * 100);
I'm dissatisfied with how the whole `getPriceThreshold()` method works. Also calling it twice in a line is kind of excessive.

I've talked with @dbelkad about it and we agreed these are due for another PR to get fixed. @dbelkad Please create a task in the backlog to describe the issue, assign it to your good self and set it's priority to low, so we can bring it in a sprint at any moment we feel you have some free time on your hands.

Once that's done I will hit the approve button :)

2022-02-15 11:03 UTC, dbelkad commented on Block/Product/View/Widget.php
>                  $threshold = (empty($this->helper->getPriceThreshold())) ? 0 : (int)($this->helper->getPriceThreshold() * 100);
Your wish is my command.

2022-02-15 11:06 UTC, dbelkad commented on Block/Product/View/Widget.php
>                  $threshold = (empty($this->helper->getPriceThreshold())) ? 0 : (int)($this->helper->getPriceThreshold() * 100);
https://divido.atlassian.net/browse/MER-282 My part of the deal is done. :)

2022-02-15 14:23 UTC, simeon-anastasov-divido commented on Block/Product/View/Widget.php
>                  $threshold = (empty($this->helper->getPriceThreshold())) ? 0 : (int)($this->helper->getPriceThreshold() * 100);
Thanks mate, so is mine :)

2022-02-15 14:24 UTC, simeon-anastasov-divido approved these changes
Let's go!

2022-02-16 08:41 UTC, joelbitar requested changes
Could we please check on the filter_var function, I'm not sure but we _might_ be introducing a bug

2022-02-16 08:41 UTC, joelbitar commented on Helper/Data.php
> +        return filter_var($threshold, FILTER_SANITIZE_NUMBER_FLOAT, $options);
I think this is a good idea! However during some simple testing I did I found If the users would input a "float" number with a decimal "," caracter, like;
"12,34" this would result in the number produced by this to be "1234", replacing all decimals with periods would solve this.

Something like;

```suggestion
        return filter_var(
            str_replace(',', '.', strval($threshold)),
            FILTER_SANITIZE_NUMBER_FLOAT,
            $options
        );
```

2022-02-16 10:00 UTC, dbelkad commented on Helper/Data.php
> +        return filter_var($threshold, FILTER_SANITIZE_NUMBER_FLOAT, $options);
You are absolutely right. My initial thought was that we don't use commas here for decimals, but didn't see the bigger picture. I stand corrected and will amend right away.

2022-02-16 10:31 UTC, simeon-anastasov-divido commented on Helper/Data.php
> +        return filter_var($threshold, FILTER_SANITIZE_NUMBER_FLOAT, $options);
I'm a much bigger fan of keeping the data at rest in a consistent state instead of manipulating it in the presentation layer, but since David told me there is no way to impose any rules on the input, then I guess this is the lesser evil :)

2022-02-16 11:42 UTC, joelbitar approved these changes
LGTM

2022-02-17 09:27 UTC, merged