fix: [LM2-294] Add field to allow for tenancy environment on plugin install
dividohq/finance-plugin-magento2 pull request #92
Opened 2021-07-29 16:11 UTC by ian-lewis-d

2021-08-13 08:12 UTC, nunocosta-divido commented on Helper/Data.php
> +            ? \Divido\MerchantSDK\Environment::CONFIGURATION[$env]['base_uri']
should this logic be inside the `getTenancyUrl` function or extracted to an helper method?

2021-08-13 08:13 UTC, nunocosta-divido commented on Helper/Data.php
> +    public function getTenancyUrl()
can we add a docblock explaining the intent behind this function and properly type hint parameters and return types?

2021-08-13 08:17 UTC, andivido approved these changes
looks good

2021-08-13 08:21 UTC, nunocosta-divido requested changes
type hints

2021-08-13 11:31 UTC, andivido commented on Helper/Data.php
> +    public function getTenancyUrl()
Type hinting is a bit tricky whilst PHP 7.3 is still supported. I think we've tried to keep the plugin 7.3 compatible in case our legacy customers haven't upgraded their servers for a while

2021-08-13 11:45 UTC, nunocosta-divido commented on Helper/Data.php
> +            ? \Divido\MerchantSDK\Environment::CONFIGURATION[$env]['base_uri']
@andivido what are your views on moving this logint inside `getTenancyUrl` or provide a default value to that function?

2021-08-13 11:52 UTC, andivido commented on Helper/Data.php
> +            ? \Divido\MerchantSDK\Environment::CONFIGURATION[$env]['base_uri']
I think that definitely makes sense

2021-08-17 12:54 UTC, joelbitar commented
> ~type hints~
> revise the `getTenancyUrl` logic

Not sure what you mean here...

2021-08-18 11:47 UTC, nunocosta-divido commented on Helper/Data.php
> +        $environmentUrl = \Divido\MerchantSDK\Environment::CONFIGURATION[$env]['base_uri'];
can this crap out with an exception ? should we be defensive and check if key $env exists

2021-08-18 11:48 UTC, nunocosta-divido commented on Helper/Data.php
> +            return '';
should we throw an error instead of returning an empty string?

2021-08-18 11:49 UTC, nunocosta-divido commented on Helper/Data.php
> +        $env = $this->getEnvironment($apiKey);
should we verify if $env is empty?

2021-08-18 12:33 UTC, joelbitar commented
I think we need to change URL to calculator javascript file

2021-08-18 12:36 UTC, joelbitar commented on Helper/Data.php
> +        $environmentUrl = \Divido\MerchantSDK\Environment::CONFIGURATION[$env]['base_uri'];
Yeah, we could do that.

2021-08-18 12:46 UTC, nunocosta-divido commented on Helper/Data.php
> +            ? \Divido\MerchantSDK\Environment::CONFIGURATION[$env]['base_uri']
> ~type hints~
> revise the `getTenancyUrl` logic

it had to do with this comment:
> @andivido what are your views on moving this logint inside `getTenancyUrl` or provide a default value to that function?



> > ~type hints~
> > revise the `getTenancyUrl` logic
> 
> Not sure what you mean here...

It had to do with this comment, https://github.com/dividohq/finance-plugin-magento2/pull/92#discussion_r688329316

but it is no longer valid

(GH only allows for request changes with a comment, that's why that cryptic message)

2021-08-18 13:00 UTC, closed without merging

2021-08-18 13:11 UTC, nunocosta-divido commented on Helper/Data.php
> +        if (empty($env) || !array_key_exists($env, \Divido\MerchantSDK\Environment::CONFIGURATION[$env])){
This looks wrong, i think it should be `if (empty($env) || !array_key_exists($env, \Divido\MerchantSDK\Environment::CONFIGURATION)){`, no `[$env]` at the end

2021-08-18 13:13 UTC, nunocosta-divido commented on Helper/Data.php
> +        $environmentUrl = \Divido\MerchantSDK\Environment::CONFIGURATION[$env]['base_uri'];
we are already checking if CONFIGURATION has a key $env on line 609, we only need to check if `base_uri` exists

2021-08-18 13:14 UTC, nunocosta-divido commented on Helper/Data.php
> +                $this->logger->info('Could not determine environment for DividoFinancing');
I think we log this message as debug not info

2021-08-18 13:14 UTC, nunocosta-divido commented on Helper/Data.php
> +                $this->logger->info('Could not determine environment for DividoFinancing');
And we should eventually log different messages with a clear indication of the reason why we failed

2021-08-18 13:18 UTC, nunocosta-divido commented on Helper/Data.php
> +        if(!is_string($environmentUrl)){
would it make more sense instead of `is_string` to use `filter_var` with the `FILTER_VALIDATE_URL` filter option?

2021-08-18 13:19 UTC, nunocosta-divido commented on Helper/Data.php
> +                $this->logger->info('Could not determine environment for DividoFinancing');
I would also argue that since we are throwing an exception we should always log the error message

2021-08-18 13:21 UTC, nunocosta-divido commented on etc/adminhtml/system.xml
> +                    <comment><![CDATA[URL Including "http://" to environment]]></comment>
maybe suggest `https` instead of http